apiVersion: 1
# https://grafana.com/docs/grafana/latest/administration/provisioning/
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true